# Generated by Django 2.2.2 on 2020-11-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('subcategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('subcategoryName', models.CharField(blank=True, max_length=255, null=True)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Category')),
            ],
            options={
                'verbose_name_plural': 'Subcategory',
            },
        ),
    ]
