# Generated by Django 2.2.2 on 2020-11-12 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('phoneNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('businessInfo', models.TextField()),
                ('itemImage', models.FileField(blank=True, null=True, upload_to='')),
                ('availableTime', models.CharField(blank=True, max_length=255, null=True)),
                ('socialMediaLink', models.CharField(blank=True, max_length=255, null=True)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Category')),
                ('cityName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.City')),
                ('item_addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemAddedBy', to=settings.AUTH_USER_MODEL)),
                ('serviceName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Service')),
                ('subcategoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Subcategory')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
