# Generated by Django 2.2.2 on 2020-11-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rp_otp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
